# Inspired from https://medium.com/@gmaliar/generating-lets-encrypt-certificates-for-nginx-using-ansible-9fd27b90993a
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install dependencies
  apt: name={{ item }} state=latest
  loop: ['python', 'python-dev', 'gcc', 'dialog', 'libaugeas0', 'augeas-lenses', 'libssl-dev', 'libffi-dev', 'ca-certificates', 'python-pip', 'python-virtualenv', 'git', 'libpython-dev', 'zlib1g-dev']

- name: Lets Encrypt client
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes

# Auto-renew certificates and reload nginx
- name: Add crontab to renew certificates
  cron:
    name: "renew certificates"
    state: present
    minute: "30"
    hour: "2"
    weekday: "1"
    job: "/opt/certbot/certbot-auto renew >> /var/log/le-renew.log"

- name: Add crontab to reload server
  cron:
    name: "reload nginx"
    state: present
    minute: "35"
    hour: "2"
    weekday: "1"
    job: "/etc/init.d/nginx reload"
