version: "3"

services:
  redis:
    container_name: telepero_redis
    image: "redis:5"
    ports:
    - "6379:6379"

  server:
    container_name: telepero_server
    build:
      context: .
      dockerfile: server.Dockerfile
    command: yarn dev
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - DEBUG=app:*
      - SECRET=devsecret
      - REDIS_HOST=telepero_redis
      - REDIS_PORT=6379
    ports:
      - "4000:4000"
    depends_on:
      - redis
