version: "3"

services:
  redis:
    container_name: redis
    image: "redis:5"
    ports:
    - "6379:6379"

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - .:/app
    environment:
      - PORT=4000
      - DEBUG=app:*
      - SECRET=devsecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "4000:4000"
    depends_on:
      - redis
